=== arctrong/md2html/java/src/main/resources/args_file_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "title": { "type": "string" },
        "logo": { "type": "string" },
        "home-page": { "type": "string" },
        "options": {
            "type": "object",
            "properties": {
                "verbose": { "type": "boolean" },
                "legacy-mode": { "type": "boolean" }
            }
        },
        "default": {
            "type": "object",
            "properties": {
                "template": { "type": "string" },
                "verbose": { "type": "boolean" },
                "input-root": { "type": "string" },
                "input": { "type": "string" },
                "input-glob": { "type": "string" },
                "sort-by-file-path": { "type": "boolean" },
                "sort-by-variable": { "type": "string" },
                "sort-by-title": { "type": "boolean" },
                "output-root": { "type": "string" },
                "output": { "type": "string" },
                "title": { "type": "string" },
                "title-from-variable": { "type": "string" },
                "code-from-variable": { "type": "string" },
                "no-css": { "type": "boolean" },
                "link-css": { "type": "array", "items": { "type": "string" } },
                "include-css": { "type": "array", "items": { "type": "string" } },
                "page-flows": { "type": "array", "items": { "type": "string" } }
            }
        },
        "documents": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "input-root": { "type": "string" },
                    "input": { "type": "string" },
                    "input-glob": { "type": "string" },
                    "sort-by-file-path": { "type": "boolean" },
                    "sort-by-variable": { "type": "string" },
                    "sort-by-title": { "type": "boolean" },
                    "output-root": { "type": "string" },
                    "output": { "type": "string" },
                    "title": { "type": "string" },
                    "title-from-variable": { "type": "string" },
                    "code": { "type": "string", "pattern": "^[\\w\\d_]+$" },
                    "code-from-variable": { "type": "string" },
                    "template": { "type": "string" },
                    "link-css": { "type": "array", "items": { "type": "string" } },
                    "include-css": { "type": "array", "items": { "type": "string" } },
                    "no-css": { "type": "boolean" },
                    "add-link-css": { "type": "array", "items": { "type": "string" } },
                    "add-include-css": { "type": "array", "items": { "type": "string" } },
                    "page-flows": { "type": "array", "items": { "type": "string" } },
                    "add-page-flows": { "type": "array", "items": { "type": "string" } },
                    "verbose": { "type": "boolean" }
                }
            }
        },
        "plugins": { "type": "object" }
    },
    "required": [ "documents" ]
}

=== arctrong/md2html/e2e_tests/test_input/BackReferencesIncrementalPluginCacheTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BackReferencesIncrementalPluginCacheTest/template.html",
        "verbose": false,
        "link-css": [
            "common_styles.css",
            "test_input/BackReferencesIncrementalPluginCacheTest/custom.css"
        ]
    },
    "documents": [
        {
            "input": "incr_plugin_cache_def.txt",
            "output": "incr_plugin_cache_def.html"
        },
        {
            "input": "incr_plugin_cache_ref_first.txt",
            "output": "incr_plugin_cache_ref_first.html"
        },
        {
            "input": "incr_plugin_cache_ref_second.txt",
            "output": "incr_plugin_cache_ref_second.html"
        }
    ],
    "plugins": {
        "back-references": {
            "cache": "test_output/common/BackReferencesIncrementalPluginCacheE2eTest/backrefs_cache.json"
        }
    }
}

=== arctrong/md2html/e2e_tests/test_input/BackReferencesPluginContentMinimalTest/md2html_args_minimal.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BackReferencesPluginContentMinimalTest/template.html",
        "verbose": false,
        "link-css": ["common_styles.css", "test_input/BackReferencesPluginContentMinimalTest/custom.css"]
    },
    "documents": [
        {
            "input": "minimal_def.txt",
            "output": "minimal_def.html"
        },
        {
            "input": "minimal_ref.txt",
            "output": "minimal_ref.html"
        }
    ],
    "plugins": {
        "back-references": {}
    }
}

=== arctrong/md2html/test/test_input/IncludeFilePluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/IncludeFilePluginTest/page_template.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "IncludeFilePlugin test" }
    ],
    "plugins": {
        "include-file": [
            { "markers": ["include_java"], "root-dir": "test_input/IncludeFilePluginTest/code/java/" },
            { "markers": ["include_shell"], "root-dir": "test_input/IncludeFilePluginTest/code/shell/", "trim": false },
            { "markers": ["include_code1", "include_code2"], "root-dir": "test_input/IncludeFilePluginTest/code/" }
        ]
    }
}

=== arctrong/md2html/e2e_tests/test_input/GlobInputTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/GlobInputTest/template.html",
        "verbose": false
    },
    "documents": [
        { "input": "single_doc.txt", "title": "Single document", "page-flows": ["all_pages"] },
        { "input-glob": "subdir01/**/*.txt", "page-flows": ["all_pages", "subdir01"], "title-from-variable": "title",
            "sort-by-file-path": true },
        { "input-glob": "subdir02/*.txt", "page-flows": ["all_pages", "subdir02"], "title-from-variable": "title",
            "sort-by-variable": "SORT_ORDER" },
        { "input-glob": "subdir03/*.txt", "page-flows": ["all_pages", "subdir03"], "title-from-variable": "title",
            "sort-by-title": true }

    ],
    "plugins": {
        "relative-paths": { "resource_path": "../doc/" },
        "page-flows": {},
        "page-variables": {}
    }
}

=== arctrong/md2html/test/test_input/PageLinksPluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/PageLinksPluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        { "input": "page1_single.txt", "title": "Page 1" },
        { "input": "page2_single.txt", "title": "Page 2", "code": "page02" },
        { "input-glob": "subdir/*.txt", "title-from-variable": "title", "code-from-variable": "code" }
    ],
    "plugins": {
        "page-variables": {},
        "page-links": {}
    }
}

=== arctrong/md2html/test/test_input/RelativePathsPluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/RelativePathsPluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "Page 1 - relative-paths" },
        { "input-glob": "subdir/*.txt", "title-from-variable": "title" }
    ],
    "plugins": {
        "page-variables": {},
        "relative-paths": { 
            "markers": ["p1", "p2"],
            "paths": { 
                "pict1": "test_input/RelativePathsPluginTest/pict1/",
                "pict2": "test_input/RelativePathsPluginTest/pict2/",
                "subdir": "test_input/RelativePathsPluginTest/subdir/"
            }
         }
    }
}

=== arctrong/md2html/test/test_input/WrapCodePluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/WrapCodePluginTest/page_template.html",
        "verbose": false,
        "link-css": ["test_input/WrapCodePluginTest/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "Page 1" }
    ],
    "plugins": {
        "page-variables": {},
        "wrap-code": {
            "wrap_java": {"style": "code",
                "template": "test_input/WrapCodePluginTest/code_template.html", "variables": {"noPageTitle": true}},
            "wrap_shell": {"style": "shell",
                "template": "test_input/WrapCodePluginTest/code_template.html", "variables": {"noPageTitle": true}},
            "wrap": {"style": "",
                "template": "test_input/WrapCodePluginTest/code_template.html", "variables": {"noPageTitle": true}}
        }
    }
}

=== arctrong/md2html/test/test_input/PageFlowsPlugin/md2html_args_new_syntax.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/PageFlowsPlugin/template_new_syntax.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        {"input": "page1.txt", "output": "new_syntax/page1.html", "title": "Page 1", 
            "page-flows": ["page_flow_1"]},
        {"input": "page2.txt", "output": "new_syntax/page2.html", "title": "Page 2", 
            "page-flows": ["page_flow_2"]},
        {"input": "page3.txt", "output": "new_syntax/page3.html", "title": "Page 3", 
            "page-flows": ["page_flow_1", "page_flow_2"]}
    ],
    "plugins": {
        "page-flows": {
            "page_flow_1": {"groups": ["group1"]},
            "page_flow_2": { "title": "Page flow 2", "groups": ["group1"], "items": [
                {"link": "https://www.google.com/", "title": "Google", "external": true}
            ]},
            "page_flow_3": { "title": "Page flow 3", "groups": ["group1"], "items": [
                {"link": "https://en.wikipedia.org/", "title": "Wikipedia", "external": true,
                    "custom_string": "custom string value", "custom_number": 101.4, 
                    "custom_boolean": true}
            ]}
        }
    }
}
