=== arctrong/md2html/java/src/main/resources/args_file_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "title": { "type": "string" },
        "logo": { "type": "string" },
        "home-page": { "type": "string" },
        "options": {
            "type": "object",
            "properties": {
                "verbose": { "type": "boolean" },
                "legacy-mode": { "type": "boolean" }
            }
        },
        "default": {
            "type": "object",
            "properties": {
                "template": { "type": "string" },
                "verbose": { "type": "boolean" },
                "input-root": { "type": "string" },
                "input": { "type": "string" },
                "input-glob": { "type": "string" },
                "sort-by-file-path": { "type": "boolean" },
                "sort-by-variable": { "type": "string" },
                "sort-by-title": { "type": "boolean" },
                "output-root": { "type": "string" },
                "output": { "type": "string" },
                "title": { "type": "string" },
                "title-from-variable": { "type": "string" },
                "code-from-variable": { "type": "string" },
                "no-css": { "type": "boolean" },
                "link-css": { "type": "array", "items": { "type": "string" } },
                "include-css": { "type": "array", "items": { "type": "string" } },
                "page-flows": { "type": "array", "items": { "type": "string" } }
            }
        },
        "documents": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "input-root": { "type": "string" },
                    "input": { "type": "string" },
                    "input-glob": { "type": "string" },
                    "sort-by-file-path": { "type": "boolean" },
                    "sort-by-variable": { "type": "string" },
                    "sort-by-title": { "type": "boolean" },
                    "output-root": { "type": "string" },
                    "output": { "type": "string" },
                    "title": { "type": "string" },
                    "title-from-variable": { "type": "string" },
                    "code": { "type": "string", "pattern": "^[\\w\\d_]+$" },
                    "code-from-variable": { "type": "string" },
                    "template": { "type": "string" },
                    "link-css": { "type": "array", "items": { "type": "string" } },
                    "include-css": { "type": "array", "items": { "type": "string" } },
                    "no-css": { "type": "boolean" },
                    "add-link-css": { "type": "array", "items": { "type": "string" } },
                    "add-include-css": { "type": "array", "items": { "type": "string" } },
                    "page-flows": { "type": "array", "items": { "type": "string" } },
                    "add-page-flows": { "type": "array", "items": { "type": "string" } },
                    "verbose": { "type": "boolean" }
                }
            }
        },
        "plugins": { "type": "object" }
    },
    "required": [ "documents" ]
}

=== arctrong/md2html/e2e_tests/test_input/BackReferencesRecursiveReplaceTest/md2html_args_ref_before_def.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BackReferencesRecursiveReplaceTest/template.html",
        "verbose": false,
        "link-css": [
            "common_styles.css",
            "test_input/BackReferencesRecursiveReplaceTest/custom.css"
        ]
    },
    "documents": [
        { "input": "ref.txt", "output": "ref.html" },
        { "input": "def.txt", "output": "def.html" }
    ],
    "plugins": {
        "replace": [
            { "markers": ["note"], "replace-with": "<!--ref ${1}--> note text",
                "recursive": true },
            { "markers": ["notedef"], "replace-with": "<!--refdef ${1} ${2}-->",
                "recursive": true }
        ],
        "back-references": {}
    }
}

=== arctrong/md2html/e2e_tests/test_input/BackReferencesPluginContentExtendedTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BackReferencesPluginContentExtendedTest/template.html",
        "verbose": false,
        "link-css": [
            "common_styles.css",
            "test_input/BackReferencesPluginContentExtendedTest/custom.css"
        ]
    },
    "documents": [
        { "input": "extended_ref_first.txt" },
        { "input": "extended_ref_second.txt" },
        { "input": "extended_multi_ref.txt" },
        { "input": "extended_multi_ref_def.txt" },
        { "input": "extended_def_com.txt" },
        { "input": "extended_def_net.txt" },
        { "input": "extended_ref_net.txt" },
        { "input": "defs/extended_subdir_def.txt" },
        { "input": "pages/extended_subdir_ref.txt" }
    ],
    "plugins": {
        "back-references": {
            "code-prefix": "xref_",
            "def-formats": [
                {
                    "markers": ["refdef"],
                    "template": "<a name=\"${anchor}\"></a><span class=\"ref-def\">[${code}]</span> ${content}<sup>${back_refs_html}</sup>",
                    "back-ref-template": "<a class=\"ref\" href=\"${href}\">${index}</a>",
                    "back-ref-delimiter": ", "
                }
            ],
            "ref-formats": [
                {
                    "markers": ["ref"],
                    "template": "${content}<sup><a name=\"${anchor}\"></a><a class=\"ref\" href=\"${href}\">[${code}]</a></sup>"
                }
            ]
        }
    }
}

=== arctrong/md2html/md2html_args.json
{
    "title": "MD2HTML",
    "logo": "doc/favicon.png",
    "home-page": "readme.html",
    "options": {
        "verbose": true,
        "cache-file": "doc/content/build_cache.json"
    },
    "default": {
        "input-root": "doc_src",
        "output-root": "doc/content",
        "template": "doc_src/templates/multipage.html",
        "no-css": true,
        "verbose": true
    },
    "documents": [
        { "input-root": "", "output-root": "", "input": "readme.txt", "title": "Home", 
            "page-flows": ["sections", "nav"] },
        { "input-glob": "sections/*.txt", "page-flows": ["sections", "nav"], 
            "title-from-variable": "title", "code-from-variable": "code", 
        "sort-by-variable": "SORT_ORDER" },
            
        { "input-glob": "sections/ref/*.txt", "page-flows": ["ref", "nav"], 
            "title-from-variable": "title", "code-from-variable": "code", 
            "sort-by-variable": "SORT_ORDER" }
    ],
    "plugins": {
        "variables": {
            "html_lang": "en",
            "burger_open_image": "layout/pict/burger.png",
            "add_powered_by": true, "ad_exec_version": true, "add_generation_timestamp": false,
            "show_source_link": true,
            "theme": "light",
            "add_more_prog_langs": true
        },
        "page-variables": {},
        "relative-paths": {
            "markers": ["path"],
            "paths": {
                "resource_path": "doc/",
                "pict": "doc/pict/",
                "doc_src": "doc_src/"
            }
        },
        "page-flows": {
            "header": [
                { "link": "readme.html", "title": "", "image": "favicon.png", "image_class": "logo_image",
                    "image_alt": "Logo" },
                { "link": "readme.html", "title": "Home", "class": "toggle_wide_only_inline" },
                { "link": "doc/content/sections/installation.html", "title": "Installation", "class": "toggle_wide_only_inline" },
                { "link": "doc/content/sections/usage.html", "title": "Usage", "class": "toggle_wide_only_inline" },
                { "link": "doc/content/index_page.html", "title": "Index", "class": "toggle_wide_only_inline" },
                { "link": "doc/content/index_page.html", "title": "", "class": "toggle_narrow_only_inline",
                    "image": "layout/pict/search.png", "image_class": "header_image index_image",
                    "image_alt": "Index" }
            ],
            "header_wide_only": [
                { "link": "https://github.com/arctrong/md2html", "title": "GitHub", "external": true }
            ],
            "sections": { "groups": ["sidebar"] },
            "ref": { "groups": ["sidebar"] }
        },
        "ignore": { "markers": ["ignore"] },
        "index": {"index": {"output": "index_page.html", "title": "Index", "index-cache": "index_cache.json", 
                    "index-cache-relative": true, "letters": true, "letters-block": true,
                    "add-link-css": ["doc/layout/index.css"] }
        },
        "page-links": { "markers": ["page"] },
        "wrap-code": {
            "wrap": {"input-root": "sample_code/", "output-root": "doc/content/code/",
                "template": "doc_src/templates/code.html", "variables": {"noPageTitle": true}}
        },
        "include-file": [
            { "markers": ["include_code"], "root-dir": "sample_code/" },
            { "markers": ["include_code_part"], "root-dir": "sample_code/", 
                "start-marker": "// INCLUDE FROM HERE" },
            { "markers": ["include_src"], "root-dir": "doc_src/", "recursive": true }
        ],
        "replace": [
            { "markers": ["red"], "replace-with": "<span style=\"color:red;\">${1}</span>" },
            { "markers": ["version"], "replace-with": "1.1.0" },
            { "markers": ["ref"], "replace-with":
                "<a class=\"ref\" href=\"<!--page refs-->#${1}\">${1}</a>",
                "recursive": true },
            { "markers": ["refdef"], "replace-with":
                "<a name=\"${1}\"></a><span class=\"refDef\">[${1}]</span>" }
        ]
    }
}

=== arctrong/md2html/e2e_tests/test_input/DeferredBuildPageTitleTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/DeferredBuildPageTitleTest/template.html",
        "verbose": false,
        "link-css": ["common_styles.css"]
    },
    "documents": [
        {
            "input": "referencer.txt",
            "output": "referencer.html"
        },
        {
            "input": "definition.txt",
            "output": "definition.html"
        },
        {
            "input": "plain.txt",
            "output": "plain.html"
        }
    ],
    "plugins": {
        "page-variables": {},
        "back-references": {}
    }
}

=== arctrong/md2html/e2e_tests/test_input/BackReferencesIncrementalBuildCacheTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BackReferencesIncrementalBuildCacheTest/template.html",
        "verbose": false,
        "link-css": [
            "common_styles.css",
            "test_input/BackReferencesIncrementalBuildCacheTest/custom.css"
        ]
    },
    "documents": [
        {
            "input": "incr_build_cache_def.txt",
            "output": "incr_build_cache_def.html"
        },
        {
            "input": "incr_build_cache_ref.txt",
            "output": "incr_build_cache_ref.html"
        }
    ],
    "plugins": {
        "back-references": {}
    }
}

=== arctrong/md2html/test/test_input/IgnorePluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/IgnorePluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "IgnorePlugin" },
        { "input": "page2.txt", "title": "IgnorePlugin2", "code": "page2" }
    ],
    "plugins": {
        "page-variables": {},
        "page-links": {},
        "ignore": {}
    }
}

=== arctrong/md2html/e2e_tests/test_input/BackReferencesRecursiveReplaceTest/md2html_args_multi_note.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BackReferencesRecursiveReplaceTest/template.html",
        "verbose": false,
        "link-css": [
            "common_styles.css",
            "test_input/BackReferencesRecursiveReplaceTest/custom.css"
        ]
    },
    "documents": [
        { "input": "ref_first.txt", "output": "ref_first.html" },
        { "input": "ref_second.txt", "output": "ref_second.html" },
        { "input": "def.txt", "output": "def.html" }
    ],
    "plugins": {
        "replace": [
            { "markers": ["note"], "replace-with": "<!--ref ${1}-->",
                "recursive": true },
            { "markers": ["notedef"], "replace-with": "<!--refdef ${1} ${2}-->",
                "recursive": true }
        ],
        "back-references": {}
    }
}

=== arctrong/md2html/test/test_input/IndexPluginTest/md2html_args_partial.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/IndexPluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "Page 1" },
        { "input": "page2.txt", "title": "Page 2" },
        { "input": "page3.txt", "title": "Page 3" }
    ],
    "plugins": {
       "variables": {"custom_variable_1": "custom value 1" },
        "index": {"output": "index_page.html", "title": "Index",
            "index-cache": "index_cache.json", "index-cache-relative": true }
    }
}
