=== arctrong/md2html/java/src/main/resources/args_file_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "title": { "type": "string" },
        "logo": { "type": "string" },
        "home-page": { "type": "string" },
        "options": {
            "type": "object",
            "properties": {
                "verbose": { "type": "boolean" },
                "legacy-mode": { "type": "boolean" }
            }
        },
        "default": {
            "type": "object",
            "properties": {
                "template": { "type": "string" },
                "verbose": { "type": "boolean" },
                "input-root": { "type": "string" },
                "input": { "type": "string" },
                "input-glob": { "type": "string" },
                "sort-by-file-path": { "type": "boolean" },
                "sort-by-variable": { "type": "string" },
                "sort-by-title": { "type": "boolean" },
                "output-root": { "type": "string" },
                "output": { "type": "string" },
                "title": { "type": "string" },
                "title-from-variable": { "type": "string" },
                "code-from-variable": { "type": "string" },
                "no-css": { "type": "boolean" },
                "link-css": { "type": "array", "items": { "type": "string" } },
                "include-css": { "type": "array", "items": { "type": "string" } },
                "page-flows": { "type": "array", "items": { "type": "string" } }
            }
        },
        "documents": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "input-root": { "type": "string" },
                    "input": { "type": "string" },
                    "input-glob": { "type": "string" },
                    "sort-by-file-path": { "type": "boolean" },
                    "sort-by-variable": { "type": "string" },
                    "sort-by-title": { "type": "boolean" },
                    "output-root": { "type": "string" },
                    "output": { "type": "string" },
                    "title": { "type": "string" },
                    "title-from-variable": { "type": "string" },
                    "code": { "type": "string", "pattern": "^[\\w\\d_]+$" },
                    "code-from-variable": { "type": "string" },
                    "template": { "type": "string" },
                    "link-css": { "type": "array", "items": { "type": "string" } },
                    "include-css": { "type": "array", "items": { "type": "string" } },
                    "no-css": { "type": "boolean" },
                    "add-link-css": { "type": "array", "items": { "type": "string" } },
                    "add-include-css": { "type": "array", "items": { "type": "string" } },
                    "page-flows": { "type": "array", "items": { "type": "string" } },
                    "add-page-flows": { "type": "array", "items": { "type": "string" } },
                    "verbose": { "type": "boolean" }
                }
            }
        },
        "plugins": { "type": "object" }
    },
    "required": [ "documents" ]
}

=== arctrong/md2html/e2e_tests/test_input/BackReferencesIncrementalPluginCacheTest/md2html_args_step2_pruned.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BackReferencesIncrementalPluginCacheTest/template.html",
        "verbose": false,
        "link-css": [
            "common_styles.css",
            "test_input/BackReferencesIncrementalPluginCacheTest/custom.css"
        ]
    },
    "documents": [
        { "input": "incr_plugin_cache_def.txt" },
        { "input": "incr_plugin_cache_ref_first.txt" }
    ],
    "plugins": {
        "back-references": {
            "cache": "test_output/common/BackReferencesIncrementalPluginCacheE2eTest/backrefs_cache.json"
        }
    }
}

=== arctrong/md2html/test/test_input/ReplacePluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/ReplacePluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/layout/content.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "ReplacePlugin" }
    ],
    "plugins": {
        "page-variables": {},
        "replace": [
            { "markers": ["replace1", "replace2"], "replace-with": "pref1+${1}+suff1" },
            { "markers": ["replace3", "replace4"], "replace-with": "pref2+${1}+middle2+${2}+suff2" }
        ]
    }
}

=== arctrong/md2html/test/test_input/PageFlowsPlugin/md2html_args_old_syntax.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/PageFlowsPlugin/template_old_syntax.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        {"input": "page1.txt", "title": "Page 1", "page-flows": ["page_flow_1"]},
        {"input": "page2.txt", "title": "Page 2", "page-flows": ["page_flow_2"]},
        {"input": "page3.txt", "title": "Page 3", "page-flows": ["page_flow_1", "page_flow_2"]}
    ],
    "plugins": {
        "page-flows": {
            "page_flow_2": [],      
            "page_flow_1": [
                {"link": "https://www.google.com/", "title": "Google", "external": true}
            ],
            "page_flow_3": [
                {"link": "https://en.wikipedia.org/", "title": "Wikipedia", "external": true,
                    "custom_string": "custom string value", "custom_number": 101.4, 
                    "custom_boolean": true}
            ]
        }
    }
}

=== arctrong/md2html/e2e_tests/test_input/BuildCacheTest/md2html_args_step2_doc_set_changed.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BuildCacheTest/template.html",
        "verbose": false,
        "link-css": ["common_styles.css"]
    },
    "documents": [
        { "input": "unchanged.txt" },
        { "input": "added_with_wrap.txt" }
    ],
    "plugins": {
        "wrap-code": {
          "wrap_java": {}
        }
    }
}

=== arctrong/md2html/e2e_tests/test_input/BackReferencesPluginContentFormatsTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BackReferencesPluginContentFormatsTest/template.html",
        "verbose": false,
        "link-css": [
            "common_styles.css",
            "test_input/BackReferencesPluginContentFormatsTest/custom.css"
        ]
    },
    "documents": [
        { "input": "formats_def_standard.txt" },
        { "input": "formats_ref_standard.txt" },
        { "input": "formats_ref_compact.txt" },
        { "input": "formats_def_bib.txt" },
        { "input": "formats_ref_bib.txt" },
        { "input": "formats_ref_bib_second.txt" },
        { "input": "formats_ref_bib_compact.txt" }
    ],
    "plugins": {
        "back-references": {
            "code-prefix": "xref_",
            "def-formats": [
                {
                    "markers": ["refdef"],
                    "template": "<a name=\"${anchor}\"></a><span class=\"ref-def\">[${code}]</span> ${content}<sup>${back_refs_html}</sup>",
                    "back-ref-template": "<a class=\"ref\" href=\"${href}\">${link_text}</a>",
                    "back-ref-delimiter": ", "
                },
                {
                    "markers": ["bibdef"],
                    "template": "<div class=\"bib-def\" id=\"${anchor}\">${content}<sup>${back_refs_html}</sup></div>",
                    "back-ref-template": "<a class=\"bib-back\" href=\"${href}\">${link_text}</a>",
                    "back-ref-delimiter": "; "
                }
            ],
            "ref-formats": [
                {
                    "markers": ["ref"],
                    "template": "${content}<sup><a name=\"${anchor}\"></a><a class=\"ref\" href=\"${href}\">[${code}]</a></sup>"
                },
                {
                    "markers": ["citeref"],
                    "template": "[<cite class=\"compact-ref\"><a name=\"${anchor}\"></a><a href=\"${href}\">${code}</a></cite>]"
                }
            ]
        }
    }
}

=== arctrong/md2html/test/test_input/IndexPluginTest/md2html_args_several.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/IndexPluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/styles.css"]
    },
    "documents": [
        { "input": "several_indexes_1.txt", "title": "Page 1", "page-flows": ["page_flow_1"] },
        { "input": "several_indexes_2.txt", "title": "Page 2", "page-flows": ["page_flow_1"] }
    ],
    "plugins": {
        "page-flows": {},
        "variables": {"custom_variable_1": "custom value 1" },
        "index": {"index1": {"output": "index_page_1.html", "title": "Index 1", "page-flows": ["page_flow_1"],
                             "index-cache": "index_cache_1.json", "index-cache-relative": true },
                  "index2": {"output": "index_page_2.html", "title": "Index 2", "page-flows": ["page_flow_1"],
                             "index-cache": "index_cache_2.json", "index-cache-relative": true } 
                 }
    }
}

=== arctrong/md2html/e2e_tests/test_input/BuildCacheIncludeDependencyTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BuildCacheIncludeDependencyTest/template.html",
        "verbose": false,
        "link-css": ["common_styles.css"]
    },
    "documents": [
        { "input": "unchanged.txt" },
        { "input": "page_a.txt" },
        { "input": "page_b.txt" }
    ],
    "plugins": {
        "include-file": [
            {
                "markers": ["include_shared"],
                "root-dir": "test_output/common/BuildCacheIncludeDependencyE2eTest/",
                "recursive": true
            }
        ]
    }
}

=== arctrong/md2html/test/test_input/BuildCacheTest/md2html_args_step1_initial.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/BuildCacheTest/template.html",
        "verbose": false,
        "link-css": ["common_styles.css"]
    },
    "documents": [
        { "input": "unchanged.txt" },
        { "input": "removed_with_wrap.txt" }
    ],
    "plugins": {
        "wrap-code": {
          "wrap_java": {}
        },
        "index": {"index": {"output": "index_page.html", "title": "Index",
            "index-cache": "index_cache.json", "index-cache-relative": true } }
    }
}
